name: C/C++ build

on: [push, pull_request]

jobs:
  ubuntu-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [g++, clang++]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Configure and Build Project
        uses: threeal/cmake-action@main
        with:
          cxx-compiler: ${{ matrix.compiler }}
