name: C/C++ build

on: [push, pull_request]

jobs:
  cmake_build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # [ubuntu-latest, macos-latest]
        compiler: [g++, clang++]
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Setup NASM
        uses: ilammy/setup-nasm@v1
      - name: Checkout
        uses: actions/checkout@v4 # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: "cpp"
      - name: Configure and Build Project
        uses: threeal/cmake-action@main
        with:
          cxx-compiler: ${{ matrix.compiler }}
      - name: Build tests
        run: cd build && make
      - name: Install test dependencies
        run: |
          sudo apt-get install -y python3.10-full \
          &&  pip install --upgrade pip \
          && pip install wheel yapf cpplint zarr xarray
      - name: Run tests
        run: |
          cd build/mdio/ \
          && ./mdio_acceptance_test \
          && ./mdio_variable_test \
          && ./mdio_dataset_test \
          && ./mdio_dataset_factory_test \
          && ./mdio_dataset_validator_test \
          && ./mdio_stats_test \
          && ./mdio_utils_test \
          && ./mdio_variable_collection_test
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
